baseURL = "https://dnscrypt.uk/"
languageCode = "en-us"

title = "dnscrypt.uk"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
#externalTitle = "dnscrypt.uk"
sidebarColor = "brown"
customCss = []

[[menu.shortcuts]]
name = "DNScrypt-Proxy on Github"
url = "https://github.com/DNSCrypt/dnscrypt-proxy"
weight = 10

[[menu.shortcuts]]
name = "DNScrypt-Proxy Wiki and Installation"
url = "https://github.com/DNSCrypt/dnscrypt-proxy/wiki"
weight = 11

[[menu.shortcuts]]
name = "DNSCrypt on Alpine Linux"
url = "https://wiki.alpinelinux.org/wiki/DNSCrypt-Proxy"
weight = 25

[[menu.shortcuts]]
name = "DNSCrypt on Arch Linux"
url = "https://wiki.archlinux.org/index.php/Dnscrypt-proxy"
weight = 26

[[menu.shortcuts]]
name = "Setup your own DNSCrypt Server in 10 minutes"
url = "https://github.com/DNSCrypt/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes"
weight = 27

[[menu.shortcuts]]
name = "DNSCrypt Info"
url = "https://dnscrypt.info"
weight = 30
